dist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure: "GkxA9AQflYbajB5jWXiBLfERVy6GcA2lah51z+qS3pVnuGkpoKMv5AA4SiSTqEzm8ADVT5Ah/6hq9M5TQVwU+qmwqdiw2WyF4PngXx11JrLpmDESgF3A6PtLBfS5DV5vJZbYg6Hu9tG+W0WupOCpvBklxrm1euoilievXNL7psHfVaSCoPlpsJQqs0qkOdJis+oEL0mdbwFTMJ2HP1R9nCV9zCvC5H0jiOJad41aZEXVVCQvwB4Ahsce0Jbg8n7X69sSuNmhpVilfw5EwPWfq8tBJU5xsgqLX7Si9MNw11vLwGDxBGrEnvlLrvF8AN4SUjdk9wvARZmLG/pKSe+EA5lvD0/aR9AKadYfWXwTOJgXBSuI7gCnY+Pzah6HjLryiX67cptesXFNBk3SbeVeahV+ga3m2Aj60IaMcHrCrAKxNynm2zWA5u7sofqP9wjpz6NCNgKQvTa6WoPusNa7fhpkeUaa4JV38Y3mTFdsTwkgwFL7MAbO1u49oNnKa0ckoWHGF1e6RCpL5RcDt/UQ9XYO1eCGT6Rfw5bNNgXFnuQNum0yYNRlORc8yTjqDQDUk+NAz8bGbY3xSSbccnZvca2Lv0mBCiiWYyz46gFOcTfAotcxvpBN87Rtv4LwO5R9J0vov88iBbOBlqRGkQny1NobZYAnhp1pHv5miEnC1LQ="
jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/dda-managed-vm-standalone.jar > target/dda-managed-vm-standalone.jar.md5
        - # create docker image
        - docker build -t dda-managed-vm --file integration/docker/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-managed-vm-test --file integration/docker/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key:
            secure: "OPJNxigck57hyJMYm97Z9X0dOlYHvGo3uYDMaDx+TuDcyg44DRy//xNmtEWSlc6mDMfn3x1k/7mv2dgBo+072lDbXhxzTGQWODNP5r0krV4P5/pv/OFoBgnASv7A/kPkmjl8WFhBMYVi/NbezXNwza4igx7VfzC+Iv+igJZZcXM2cUQbu/lRnCZEOOkM8OKFSMMB0d4Tb4mknzYeZRNYPsWvi5mIt6B3qT1ScTV8Ow9xDVxfQ64o+F1AUd5wsyTm2no71v2aeresQaH8uzuNfGwlx/ACIrV6JLXN6y3a5wmMTgvElnghs2LCA4i2k1Pvkg8Pg8tpRGBqkf1EVr2lHi8LVCfrESC2aT6tzxBM0lVAkxK6fPnjd/wDnEWUu8OK5mkjNuK1OFh8FAD8dTlVAW2Sg6h8igWI6OVvr9ZvURcnRQ22HoLUTB43rt9OKeBPHRsaPpI6fdalVMs2qz+hBgM837JGVy6dZHfl2Su9Q6L0edQ2UQjtrt/zvex0i1SHZ+62CmMbTlwnTRA9HLXOJodhmuY30J0qvdSWdAnBbJx80Ik2oHcEEQYCBYLdmiJzQv6NjwZ/Wb+CuoSzesW2i0BCj1Nd/h/S6iew/hRQGTkdI+jAneKanbJIDhaTOYlqqylaH0HF3KnxXwZ1ievWkacS03e0wBy+m0R7OFNVDRY="
          file:
            - target/dda-managed-vm-standalone.jar
            - target/dda-managed-vm-standalone.jar.md5
